/**
 * Document en cours de validation par le
 * CGTI (Consortium de la Grande Toile Internationale [ex W3C])
 */

export default {
  'animation-delay': 'délai-animation',
  'animation-direction': 'direction-animation',
  'animation-duration': 'durée-animation',
  'animation-fill-mode': 'mode-remplissage-animation',
  'animation-iteration-count': 'nombre-itérations-animation',
  'animation-name': 'nom-animation',
  'animation-play-state': 'état-animation',
  'animation-timing-function': 'fonction-déroulement-animation',
  'animation': 'animation',
  'background-attachment': 'attachement-du-fond',
  'background-clip': 'coupure-du-fond',
  'background-color': 'couleur-du-fond',
  'background-image': 'image-du-fond',
  'background-origin': 'origine-du-fond',
  'background-position': 'position-du-fond',
  'background-repeat': 'répétition-du-fond',
  'background-size': 'taille-du-fond',
  'background': 'fond',
  'border-bottom-color': 'couleur-de-la-bordure-du-bas',
  'border-bottom-left-radius': 'rayon-gauche-de-la-bordure-du-bas',
  'border-bottom-right-radius': 'rayon-droit-de-la-bordure-du-bas',
  'border-bottom-style': 'style-de-la-bordure-du-bas',
  'border-bottom-width': 'épaisseur-de-la-bordure-du-bas',
  'border-bottom': 'bordure-du-bas',
  'border-collapse': 'fusion-des-bordures',
  'border-color': 'couleur-des-bordures',
  'border-image': 'image-des-bordures',
  'border-image-outset': 'dépassement-imgae-des-bordures',
  'border-image-repeat': 'répétition-image-des-bordures',
  'border-image-slice': 'coupure-image-des-bordures',
  'border-image-source': 'source-image-des-bordures',
  'border-image-width': 'épaisseur-image-des-bordures',
  'border-left-color': 'couleur-de-la-bordure-de-gauche',
  'border-left-style': 'style de la bordure de gauche',
  'border-left-width': 'épaisseur de la bordure de gauche',
  'border-left': 'bordure de gauche',
  'border-radius': 'rayon des coins',
  'border-right-color': 'couleur de la bordure de droite'
}
