/**
 * Document en cours de validation par le
 * CGTI (Consortium de la Grande Toile Internationale [ex W3C])
 */

export default {
  // '::after (:after)': '::après (:après)',
  // '::backdrop': '::justeaprès',
  // '::before (:before)': '::avant (:avant)',
  // '::first-letter (:first-letter)': '::première-lettre (:première-letre)',
  // '::first-line (:first-line)': '::première-ligne (:première-ligne)',
  // '::repeat-index': '::index-de-répétition',
  // '::repeat-item': '::répéter-objet',
  // '::selection': '::sélection',
  // ':checked': ':coché',
  // ':default': ':défaut',
  // ':dir()': ':direction()',
  // ':disabled': ':désactivé',
  // ':empty': ':vide',
  // ':enabled': ':activé',
  // ':first': ':premier',
  // ':first-child': ':premier-enfant',
  // ':first-of-type': ':premier-du-type',
  // ':focus': ':regardé',
  // ':fullscreen': ':plein-écran',
  // ':hover': ':survolé',
  // ':in-range': 'dans-la-gamme',
  // ':indeterminate': 'indéterminé',
  // ':invalid': ':invalide',
  // ':lang()': ':langue()',
  // ':last-child': ':dernier-enfant',
  // ':last-of-type': ':dernier-du-type',
  // ':left': ':gauche',
  // ':link': ':lien',
  // ':not()': ':pas()',
  // ':nth-child()': ':ième-enfant()',
  // ':nth-last-child()': 'ième-dernier-enfant()',
  // ':nth-last-of-type()': 'ième-dernier-du-type()',
  // ':nth-of-type()': 'ième-du-type()',
  // ':only-child': ':fils-unique',
  // ':only-of-type': ':seul-du-type',
  // ':optional': ':optionnel',
  // ':out-of-range': ':hors-de-gamme',
  // ':read-only': ':lecture-seulement',
  // ':read-write': ':lecture-ecriture',
  // ':required': ':requis',
  // ':right': ':droite',
  // ':root': ':racine',
  // ':scope': ':portée',
  // ':target': ':cible',
  // ':unresolved': ':non-résolu',
  // ':valid': ':valide',
  // ':visited': ':visité',
  '<angle>': '<angle>',
  '<basic-shape>': '<forme-simple>',
  '<blend-mode>': '<mode-mélangé>',
  '<color>': '<couleur>',
  '<counter>': '<compteur>',
  '<custom-ident>': '<>',
  '<frequency>': '<fréquence>',
  '<gradient>': '<dégradé>',
  '<image>': '<image>',
  '<integer>': '<entier>',
  '<length>': '<longueur>',
  '<number>': '<nombre>',
  '<percentage>': '<pourcentage>',
  '<position>': '<position>',
  '<ratio>': '<ratio>',
  '<resolution>': '<résolution>',
  '<shape>': '<forme>',
  '<string>': '<chaine>',
  '<time>': '<temps>',
  '<timing-function>': '<fonction-temporelle>',
  '<transform-function>()': '<fonction-de-transformation>()',
  '<url>': '<adresse-web>',
  // '@charset': '@ensemble-de-caractères',
  // '@counter-style': '@style-de-compteur',
  // '@document': '@document',
  // '@font-face': '@type-typographie',
  // '@font-feature-values': '@valeur-des-fonctions-de-typographie',
  // '@import': '@import',
  // '@keyframes': '@images-clef',
  // '@media': '@média',
  // '@namespace': '@espace-de-nommage',
  // '@ornaments': '@ornements',
  // '@page': '@page',
  // '@styleset': '@ensemble-de-style',
  // '@stylistic': '@stylistique',
  // '@supports': '@supporte',
  // '@viewport': '@fenêtre',
  'additive-symbols': 'symboles-aditionnels',
  'align-content': 'alignement-du-contenu',
  'align-items': 'alignement-des-éléments',
  'align-self': 'aligements-de-lui-même',
  'all': 'tout',
  'animation': 'animation',
  'animation-delay': 'délai-animation',
  'animation-direction': 'direction-animation',
  'animation-duration': 'durée-animation',
  'animation-fill-mode': 'mode-remplissage-animation',
  'animation-iteration-count': 'nombre-itérations-animation',
  'animation-name': 'nom-animation',
  'animation-play-state': 'état-animation',
  'animation-timing-function': 'fonction-déroulement-animation',
  'attr()': 'attribut()',
  'backface-visibility': 'visibilité-de-la-face-arrière',
  'background': 'fond',
  'background-attachment': 'attachement-du-fond',
  'background-blend-mode': 'mode-fusion-du-fond',
  'background-clip': 'coupure-du-fond',
  'background-color': 'couleur-du-fond',
  'background-image': 'image-du-fond',
  'background-origin': 'origine-du-fond',
  'background-position': 'position-du-fond',
  'background-repeat': 'répétition-du-fond',
  'background-size': 'taille-du-fond',
  'block-size': 'taille-du-bloc',
  'blur()': 'flou()',
  'border': 'bordure()',
  'border-block-end': 'bordure-du-bloc-de-fin',
  'border-block-end-color': 'couleur-de-la-bordure-du-bloc-de-fin',
  'border-block-end-style': 'style-de-la-bordure-du-bloc-de-fin',
  'border-block-end-width': 'largeur-de-la-bordure-du-bloc-de-fin',
  'border-block-start': 'bordure-du-bloc-de-début',
  'border-block-start-color': 'couleur-de-la-bordure-du-bloc-de-début',
  'border-block-start-style': 'style-de-la-bordure-du-bloc-de-début',
  'border-block-start-width': 'largeur-de-la-bordure-du-bloc-de-début',
  'border-bottom': 'bordure-du-bas',
  'border-bottom-color': 'couleur-de-la-bordure-du-bas',
  'border-bottom-left-radius': 'rayon-gauche-de-la-bordure-du-bas',
  'border-bottom-right-radius': 'rayon-droit-de-la-bordure-du-bas',
  'border-bottom-style': 'style-de-la-bordure-du-bas',
  'border-bottom-width': 'épaisseur-de-la-bordure-du-bas',
  'border-collapse': 'fusion-des-bordures',
  'border-color': 'couleur-des-bordures',
  'border-image': 'image-des-bordures',
  'border-image-outset': 'dépassement-des-image-des-bordures',
  'border-image-repeat': 'répétition-des-image-des-bordures',
  'border-image-slice': 'coupure-des-image-des-bordures',
  'border-image-source': 'source-des-image-des-bordures',
  'border-image-width': 'épaisseur-des-image-des-bordures',
  'border-inline-end': 'fin-de-la-bordure-en-ligne',
  'border-inline-end-color': 'fin-de-la-bordure-en-ligne-couleur',
  'border-inline-end-style': 'fin-de-la-bordure-en-ligne-style',
  'border-inline-end-width': 'fin-de-la-bordure-en-ligne-largeur',
  'border-inline-start': 'début-bordure-en-ligne',
  'border-inline-start-color': 'début-bordure-en-ligne-couleur',
  'border-inline-start-style': 'début-bordure-en-ligne-style',
  'border-inline-start-width': 'début-bordure-en-ligne-largeur',
  'border-left': 'bordure-gauche',
  'border-left-color': 'couleur-de-la-bordure-de-gauche',
  'border-left-style': 'style-de-la-bordure-de-gauche',
  'border-left-width': 'épaisseur-de-la-bordure-de-gauche',
  'border-radius': 'rayon-des-coins',
  'border-right': 'bordure-de-droite',
  'border-right-color': 'couleur-de-la-bordure-de-droite',
  'border-right-style': 'style-de-la-bordure-de-droite',
  'border-right-width': 'épaisseur-de-la-bordure-de-droite',
  'border-spacing': 'espacement-de-la-bordure',
  'border-style': 'style-de-la-bordure',
  'border-top': 'bordure-du-haut',
  'border-top-color': 'couleur-de-la-bordure-du-haut',
  'border-top-left-radius': 'rayon-gauche-de-la-bordure-du-haut',
  'border-top-right-radius': 'rayon-droit-de-la-bordure-du-haut',
  'border-top-style': 'style-de-la-bordure-du-haut',
  'border-top-width': 'largeur-de-la-bordure-du-haut',
  'border-width': 'largeur-de-la-bordure',
  'bottom': 'bas',
  'box-decoration-break': 'fragmentation-de-la-décoration-de-boite',
  'box-shadow': 'ombre-de-boite',
  'box-sizing': 'taille-de-boite',
  'break-after': 'saut-après',
  'break-before': 'saut-avant',
  'break-inside': 'saut-dedans',
  'brightness()': 'luminosité()',
  'calc()': 'calcul()',
  'caption-side': 'côté-de-la-légence',
  'character-variant()': 'variance-de-caractère',
  'circle()': 'cercle()',
  'clear': 'nettoyer',
  'clip': 'attacher',
  'clip-path': 'chemin-attache',
  'color': 'couleur',
  'column-count': 'compte-de-colone',
  'column-fill': 'remplissage-de-colone',
  'column-gap': 'marge-de-colone',
  'column-rule': 'règle-de-colone',
  'column-rule-color': 'couleur-de-la-règle-de-colone',
  'column-rule-style': 'style-de-la-règle-de-colone',
  'column-rule-width': 'largeur--de-la-règle-de-colone',
  'column-span': 'envergure-de-colone',
  'column-width': 'largeur-de-colone',
  'columns': 'colone',
  // 'content': '',
  // 'contrast()': '',
  // 'counter-increment': '',
  // 'counter-reset': '',
  // 'cubic-bezier()': '',
  // 'cursor': '',
  // 'deg': '',
  // 'direction': '',
  // 'display': '',
  // 'dpcm': '',
  // 'dpi': '',
  // 'dppx': '',
  // 'drop-shadow()': '',
  // 'element()': '',
  // 'ellipse()': '',
  // 'em': '',
  // 'empty-cells': '',
  // 'end-mode': '',
  // 'ex': '',
  // 'fallback': '',
  // 'filter': '',
  // 'flex': '',
  // 'flex-basis': '',
  // 'flex-direction': '',
  // 'flex-flow': '',
  // 'flex-grow': '',
  // 'flex-shrink': '',
  // 'flex-wrap': '',
  // 'float': '',
  // 'font': 'typographie',
  // 'font-family (descriptor)': 'typographie',
  // 'font-family (property)': 'typographie',
  // 'font-feature-settings (descriptor)': 'typographie',
  // 'font-feature-settings (property)': 'typographie',
  // 'font-kerning': 'typographie',
  // 'font-language-override': 'typographie',
  // 'font-size': 'typographie',
  // 'font-size-adjust': 'typographie',
  // 'font-stretch (descriptor)': 'typographie',
  // 'font-stretch (property)': 'typographie',
  // 'font-style (descriptor)': 'typographie',
  // 'font-style (property)': 'typographie',
  // 'font-synthesis': 'typographie',
  // 'font-variant (descriptor)': 'typographie',
  // 'font-variant (property)': 'typographie',
  // 'font-variant-alternates': 'typographie',
  // 'font-variant-caps': 'typographie',
  // 'font-variant-east-asian': 'typographie',
  // 'font-variant-ligatures': 'typographie',
  // 'font-variant-numeric': 'typographie',
  // 'font-variant-position': 'typographie',
  // 'font-weight (descriptor)': 'typographie',
  // 'font-weight (property)': 'typographie',
  // 'grad': '',
  // 'grayscale()': '',
  // 'grid': '',
  // 'grid-area': '',
  // 'grid-auto-columns': '',
  // 'grid-auto-flow': '',
  // 'grid-auto-rows': '',
  // 'grid-column': '',
  // 'grid-column-end': '',
  // 'grid-column-gap': '',
  // 'grid-column-start': '',
  // 'grid-gap': '',
  // 'grid-row': '',
  // 'grid-row-end': '',
  // 'grid-row-gap': '',
  // 'grid-row-start': '',
  // 'grid-template': '',
  // 'grid-template-areas': '',
  // 'grid-template-columns': '',
  // 'grid-template-rows': '',
  // 'height': '',
  // 'hsl()': '',
  // 'hsla()': '',
  // 'hue-rotate()': '',
  // 'hyphens': '',
  // 'hz': '',
  // 'image()': '',
  // 'image-orientation': '',
  // 'image-rendering': '',
  // 'image-resolution': '',
  // 'ime-mode': '',
  // 'in': '',
  // 'inherit': '',
  // 'initial': '',
  // 'inline-size': '',
  // 'inset()': '',
  // 'invert()': '',
  // 'isolation': '',
  // 'justify-content': '',
  // 'khz': '',
  // 'left': '',
  // 'letter-spacing': '',
  // 'line-break': '',
  // 'line-height': '',
  // 'linear-gradient()': '',
  // 'list-style': '',
  // 'list-style-image': '',
  // 'list-style-position': '',
  // 'list-style-type': '',
  // 'margin': '',
  // 'margin-block-end': '',
  // 'margin-block-start': '',
  // 'margin-bottom': '-bas',
  // 'margin-inline-end': '',
  // 'margin-inline-start': '',
  // 'margin-left': '',
  // 'margin-right': '',
  // 'margin-top': '',
  // 'marks': '',
  // 'mask': '',
  // 'mask-clip': '',
  // 'mask-composite': '',
  // 'mask-image': '',
  // 'mask-mode': '',
  // 'mask-origin': '',
  // 'mask-position': '',
  // 'mask-repeat': '',
  // 'mask-size': '',
  // 'mask-type': '',
  // 'matrix()': '',
  // 'matrix3d()': '',
  // 'max-block-size': '',
  // 'max-height': '',
  // 'max-inline-size': '',
  // 'max-width': '',
  // 'max-zoom': '',
  // 'min-block-size': '',
  // 'min-height': '',
  // 'min-inline-size': '',
  // 'min-width': '',
  // 'min-zoom': '',
  // 'minmax()': '',
  // 'mix-bl': '',
  // 'mm': '',
  // 'ms': '',
  // 'negative': '',
  // 'object-fit': '',
  // 'object-position': '',
  // 'offset-block-end': '',
  // 'offset-block-start': '',
  // 'offset-inline-end': '',
  // 'offset-inline-start': '',
  // 'opacity': '',
  // 'opacity()': '',
  // 'order': '',
  // 'orientation': '',
  // 'ornaments()': '',
  // 'orphans': '',
  // 'outline': '',
  // 'outline-color': '',
  // 'outline-offset': '',
  // 'outline-style': '',
  // 'outline-width': '',
  // 'overflow': '',
  // 'overflow-wrap': '',
  // 'overflow-x': '',
  // 'overflow-y': '',
  // 'pad': '',
  'padding': 'rembourrage',
  'padding-block-end': 'rembourrage-du-bas-du-bloc',
  'padding-block-start': 'rembourrage-du-début-du-bloc',
  'padding-inline-end': 'fin-du-rembourrage-en-ligne',
  'padding-inline-start': 'début-du-rembourrage-du-bas',
  'padding-bottom': 'rembourrage-bas',
  'padding-left': 'rembourrage-gauche',
  'padding-right': 'rembourrage-droit',
  'padding-top': 'rembourrage-haut',
  // 'page-break-after': '',
  // 'page-break-before': '',
  // 'page-break-inside': '',
  // 'pc': '',
  // 'perspective': '',
  // 'perspective()': '',
  // 'perspective-origin': '',
  // 'pointer-events': '',
  // 'polygon()': '',
  // 'position': '',
  // 'prefix': '',
  // 'pt': '',
  // 'px': '',
  // 'quotes': '',
  // 'rad': '',
  // 'radial-gradient()': '',
  // 'range': '',
  // 'rect()': '',
  // 'rem': '',
  // 'repeat()': '',
  // 'repeating-linear-gradient()': '',
  // 'repeating-radial-gradient()': '',
  // 'resize': '',
  // 'revert': '',
  'rgb()': 'rvb()',
  'rgba()': 'rvbo()',
  'right': 'droite',
  // 'rotate()': '',
  // 'rotate3d()': '',
  // 'rotatex()': '',
  // 'rotatey()': '',
  // 'rotatez()': '',
  // 'ruby-align': '',
  // 'ruby-merge': '',
  // 'ruby-position': '',
  // 's': '',
  // 'saturate()': '',
  // 'scale()': '',
  // 'scale3d()': '',
  // 'scalex()': '',
  // 'scaley()': '',
  // 'scalez()': '',
  // 'scroll-behavior': '',
  // 'scroll-snap-coordinate': '',
  // 'scroll-snap-destination': '',
  // 'scroll-snap-type': '',
  // 'sepia()': '',
  // 'shape-image-threshold': '',
  // 'shape-margin': '',
  // 'shape-outside': '',
  // 'skew()': '',
  // 'skewx()': '',
  // 'skewy()': '',
  // 'speak-as': '',
  // 'src': '',
  // 'steps()': '',
  // 'styleset()': '',
  // 'stylistic()': '',
  // 'suffix': '',
  // 'swash()': '',
  // 'symbols': '',
  // 'symbols()': '',
  // 'system': '',
  // 'tab-size': '',
  // 'table-layout': '',
  // 'text-align': '',
  // 'text-align-last': '',
  // 'text-combine-upright': '',
  // 'text-decoration': '',
  // 'text-decoration-color': '',
  // 'text-decoration-line': '',
  // 'text-decoration-style': '',
  // 'text-emphasis': '',
  // 'text-emphasis-color': '',
  // 'text-emphasis-position': '',
  // 'text-emphasis-style': '',
  // 'text-indent': '',
  // 'text-orientation': '',
  // 'text-overflow': '',
  // 'text-rendering': '',
  // 'text-shadow': '',
  // 'text-transform': '',
  // 'text-underline-position': '',
  // 'top': '',
  // 'touch-action': '',
  // 'transform': '',
  // 'transform-box': '',
  // 'transform-origin': '',
  // 'transform-style': '',
  // 'transition': '',
  // 'transition-delay': '',
  // 'transition-duration': '',
  // 'transition-property': '',
  // 'transition-timing-function': '',
  // 'translate()': '',
  // 'translate3d()': '',
  // 'translatex()': '',
  // 'translatey()': '',
  // 'translatez()': '',
  // 'turn': '',
  // 'unicode-bidi': '',
  // 'unicode-range': '',
  // 'unset': '',
  // 'url()': '',
  // 'user-zoom': '',
  // 'var()': '',
  // 'vertical-align': '',
  // 'vh': '',
  // 'visibility': '',
  // 'vmax': '',
  // 'vmin': '',
  // 'vw': '',
  // 'white-space': '',
  // 'widows': '',
  // 'width': '',
  // 'will-change': '',
  // 'word-break': '',
  // 'word-spacing': '',
  // 'word-wrap': '',
  // 'writing-mode': '',
  // 'z-index': '',
  // 'zoom': '',
}
